# Generated by Django 4.0.5 on 2022-09-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagem',
            old_name='produtos',
            new_name='produto',
        ),
    ]
