# Generated by Django 4.0.5 on 2022-09-26 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_produto_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='slug',
        ),
    ]
